@echo off
echo Installing Python dependencies...
pip install fastapi uvicorn httpx pydantic python-dotenv

echo Cleaning up old background processes on port 8002...
for /f "tokens=5" %%a in ('netstat -a -n -o ^| findstr :8002') do taskkill /f /pid %%a 2>nul

echo Starting Python Backend...
start cmd /k "title AI Backend Server & echo Starting FastAPI Server... & python backend.py || echo. & echo [ERROR] THE SERVER CRASHED! Please copy the error message above and paste it in the chat. & pause"

echo Installing Node dependencies...
npm install

echo Starting React Frontend...
npm run dev
